name: Notify Slack on Discussion Comment

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJSON(github.event) }}"
    - name: Determine Slack Webhook URL
      id: determine_url
      run: |
        CATEGORY_NAME="${{ github.event.discussion.category.name }}"
        if [[ "$CATEGORY_NAME" == *"FE"* && "$CATEGORY_NAME" == *"BE"* ]]; then
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_OTHER }}" >> $GITHUB_ENV
        elif [[ "$CATEGORY_NAME" == *"FE"* ]]; then
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_FE }}" >> $GITHUB_ENV
        elif [[ "$CATEGORY_NAME" == *"BE"* ]]; then
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_BE }}" >> $GITHUB_ENV
        else
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_OTHER }}" >> $GITHUB_ENV
        fi

    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ env.WEBHOOK_URL }}
      run: |
        COMMENT_CREATED_AT="${{ github.event.comment.created_at }}"
        COMMENT_TIMESTAMP=$(date -d "$COMMENT_CREATED_AT" +%s)
        COMMENT_URL="${{ github.event.comment.html_url }}"
        COMMENT_BODY="${{ github.event.comment.body }}"
        COMMENT_USER="${{ github.event.comment.user.login }}"
        COMMENT_USER_AVATAR="${{ github.event.comment.user.avatar_url }}"
        DISCUSSION_TITLE="${{ github.event.discussion.title }}"
        DISCUSSION_NUMBER="${{ github.event.discussion.number }}"
        DISCUSSION_CATEGORY="${{ github.event.discussion.category.name }}"
        REPO_NAME="${{ github.event.repository.name }}"

        curl -X POST -H 'Content-type: application/json' --data '{
          "username": "GitHub Discussions",
          "icon_url": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
          "text": "<'"$COMMENT_URL"'|Comment on #'"$DISCUSSION_NUMBER"' '"$DISCUSSION_TITLE"'>",
          "attachments": [
            {
              "fallback": "コメントが追加されました！",
              "author_name": "'"$COMMENT_USER"'",
              "author_icon": "'"$COMMENT_USER_AVATAR"'",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*New comment on discussion:*\n<'"$COMMENT_URL"'|View Comment>\n\n*Comment:*\n'"$COMMENT_BODY"'\n\n*Created at:*\n'"$COMMENT_CREATED_AT"'"
                  }
                }
              ],
              "footer": "'"$DISCUSSION_CATEGORY"' #'"$DISCUSSION_NUMBER"' '"$DISCUSSION_TITLE"' '"$REPO_NAME"'",
              "ts": '"$COMMENT_TIMESTAMP"'
            }
          ]
        }' $SLACK_WEBHOOK_URL
