name: Notify Slack on Discussion Comment

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJSON(github.event.discussion) }}"
    - name: Determine Slack Webhook URL
      id: determine_url
      run: |
        CATEGORY_NAME="${{ github.event.discussion.category.name }}"
        if [[ "$CATEGORY_NAME" == *"FE"* && "$CATEGORY_NAME" == *"BE"* ]]; then
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_OTHER }}" >> $GITHUB_ENV
        elif [[ "$CATEGORY_NAME" == *"FE"* ]]; then
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_FE }}" >> $GITHUB_ENV
        elif [[ "$CATEGORY_NAME" == *"BE"* ]]; then
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_BE }}" >> $GITHUB_ENV
        else
          echo "WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_OTHER }}" >> $GITHUB_ENV
        fi

    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ env.WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "New comment on discussion: ${{ github.event.discussion.html_url }}\nComment: ${{ github.event.comment.body }}",
          "unfurl_links": true
          
        }' $SLACK_WEBHOOK_URL
