name: Notify Slack on Discussion Comment

on:
  discussion:
    types: [created]
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Determine Slack Webhook URL
      id: determine_url
      run: |
        CATEGORY_NAME="${{ github.event.discussion.category.name }}"
        WEBHOOK_URLS=()
        if [[ "$CATEGORY_NAME" == *"FE"* ]]; then
          WEBHOOK_URLS+=("${{ secrets.SLACK_WEBHOOK_URL_FE }}")
        fi
        if [[ "$CATEGORY_NAME" == *"BE"* ]]; then
          WEBHOOK_URLS+=("${{ secrets.SLACK_WEBHOOK_URL_FE }}")
        fi
        if [[ ${#WEBHOOK_URLS[@]} -eq 0 ]]; then
          WEBHOOK_URLS+=("${{ secrets.SLACK_WEBHOOK_URL_OTHER }}")
        fi
        echo "WEBHOOK_URLS=${WEBHOOK_URLS[@]}" >> $GITHUB_ENV
    
    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URLS: ${{ env.WEBHOOK_URLS }}
      run: |
        COMMENT_URL="${{ github.event.discussion.html_url }}"
        COMMENT_BODY="${{ github.event.discussion.body }}"
        COMMENT_CREATED_AT="${{ github.event.discussion.created_at }}"
        DISCUSSION_NUMBER="${{ github.event.discussion.number }}"
        DISCUSSION_TITLE="${{ github.event.discussion.title }}"
        DISCUSSION_URL="${{ github.event.discussion.html_url }}"
        DISCUSSION_CATEGORY="${{ github.event.discussion.category.name }}"
        REPOSITORY_URL="${{ github.event.repository.html_url }}"
        REPOSITORY_NAME="${{ github.event.repository.full_name }}"
        COMMENT_USER="${{ github.event.discussion.user.login }}"
        COMMENT_USER_AVATAR="${{ github.event.discussion.user.avatar_url }}"
        
        # Convert the created_at timestamp to a Unix timestamp
        COMMENT_TIMESTAMP=$(date -d "$COMMENT_CREATED_AT" +%s)
        
        
        # Create the JSON payload for Slack
        PAYLOAD=$(jq -n --arg url "$COMMENT_URL" \
                        --arg body "$COMMENT_BODY" \
                        --arg created_at "$COMMENT_CREATED_AT" \
                        --arg discussion_number "$DISCUSSION_NUMBER" \
                        --arg discussion_title "$DISCUSSION_TITLE" \
                        --arg discussion_url "$DISCUSSION_URL" \
                        --arg discussion_category "$DISCUSSION_CATEGORY" \
                        --arg repository_url "$REPOSITORY_URL" \
                        --arg repository_name "$REPOSITORY_NAME" \
                        --arg comment_user "$COMMENT_USER" \
                        --arg comment_user_avatar "$COMMENT_USER_AVATAR" \
                        --arg ts "$COMMENT_TIMESTAMP" '{
          "username": "GitHub Discussions",
          "icon_url": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
          "text": "New discussion created",
          "attachments": [
            {
              "fallback": "新しいディスカッションが作成されました！",
              "author_name": $comment_user,
              "author_icon": $comment_user_avatar,
              "title": $discussion_title,
              "title_link": $discussion_url,
              "text": $body,
              "footer": "<\($discussion_url)|\($discussion_category)> <\($repository_url)|\($repository_name)> Sent by GitHub Actions",
              "ts": $ts
            }
          ]
        }')
        
        # Send the payload to each Slack webhook URL
        for WEBHOOK_URL in $WEBHOOK_URLS; do
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $WEBHOOK_URL
        done
